/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ChannelsRouteImport } from './routes/channels'
import { Route as InboxRouteImport } from './routes/inbox'
import { Route as LaterRouteImport } from './routes/later'
import { Route as LibraryRouteImport } from './routes/library'
import { Route as LiveRouteImport } from './routes/live'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PulseRouteImport } from './routes/pulse'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ShortsRouteImport } from './routes/shorts'
import { Route as YouRouteImport } from './routes/you'
import { Route as ChannelChannelIdRouteImport } from './routes/channel.$channelId'
import { Route as WatchVideoIdRouteImport } from './routes/watch.$videoId'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChannelsRoute = ChannelsRouteImport.update({
  id: '/channels',
  path: '/channels',
  getParentRoute: () => rootRouteImport,
} as any)
const InboxRoute = InboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => rootRouteImport,
} as any)
const LaterRoute = LaterRouteImport.update({
  id: '/later',
  path: '/later',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryRoute = LibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => rootRouteImport,
} as any)
const LiveRoute = LiveRouteImport.update({
  id: '/live',
  path: '/live',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PulseRoute = PulseRouteImport.update({
  id: '/pulse',
  path: '/pulse',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ShortsRoute = ShortsRouteImport.update({
  id: '/shorts',
  path: '/shorts',
  getParentRoute: () => rootRouteImport,
} as any)
const YouRoute = YouRouteImport.update({
  id: '/you',
  path: '/you',
  getParentRoute: () => rootRouteImport,
} as any)
const ChannelChannelIdRoute = ChannelChannelIdRouteImport.update({
  id: '/channel/$channelId',
  path: '/channel/$channelId',
  getParentRoute: () => rootRouteImport,
} as any)
const WatchVideoIdRoute = WatchVideoIdRouteImport.update({
  id: '/watch/$videoId',
  path: '/watch/$videoId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/channels': typeof ChannelsRoute
  '/inbox': typeof InboxRoute
  '/later': typeof LaterRoute
  '/library': typeof LibraryRoute
  '/live': typeof LiveRoute
  '/login': typeof LoginRoute
  '/pulse': typeof PulseRoute
  '/settings': typeof SettingsRoute
  '/shorts': typeof ShortsRoute
  '/you': typeof YouRoute
  '/channel/$channelId': typeof ChannelChannelIdRoute
  '/watch/$videoId': typeof WatchVideoIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/channels': typeof ChannelsRoute
  '/inbox': typeof InboxRoute
  '/later': typeof LaterRoute
  '/library': typeof LibraryRoute
  '/live': typeof LiveRoute
  '/login': typeof LoginRoute
  '/pulse': typeof PulseRoute
  '/settings': typeof SettingsRoute
  '/shorts': typeof ShortsRoute
  '/you': typeof YouRoute
  '/channel/$channelId': typeof ChannelChannelIdRoute
  '/watch/$videoId': typeof WatchVideoIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/channels': typeof ChannelsRoute
  '/inbox': typeof InboxRoute
  '/later': typeof LaterRoute
  '/library': typeof LibraryRoute
  '/live': typeof LiveRoute
  '/login': typeof LoginRoute
  '/pulse': typeof PulseRoute
  '/settings': typeof SettingsRoute
  '/shorts': typeof ShortsRoute
  '/you': typeof YouRoute
  '/channel/$channelId': typeof ChannelChannelIdRoute
  '/watch/$videoId': typeof WatchVideoIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/channels'
    | '/inbox'
    | '/later'
    | '/library'
    | '/live'
    | '/login'
    | '/pulse'
    | '/settings'
    | '/shorts'
    | '/you'
    | '/channel/$channelId'
    | '/watch/$videoId'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/channels'
    | '/inbox'
    | '/later'
    | '/library'
    | '/live'
    | '/login'
    | '/pulse'
    | '/settings'
    | '/shorts'
    | '/you'
    | '/channel/$channelId'
    | '/watch/$videoId'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/channels'
    | '/inbox'
    | '/later'
    | '/library'
    | '/live'
    | '/login'
    | '/pulse'
    | '/settings'
    | '/shorts'
    | '/you'
    | '/channel/$channelId'
    | '/watch/$videoId'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChannelsRoute: typeof ChannelsRoute
  InboxRoute: typeof InboxRoute
  LaterRoute: typeof LaterRoute
  LibraryRoute: typeof LibraryRoute
  LiveRoute: typeof LiveRoute
  LoginRoute: typeof LoginRoute
  PulseRoute: typeof PulseRoute
  SettingsRoute: typeof SettingsRoute
  ShortsRoute: typeof ShortsRoute
  YouRoute: typeof YouRoute
  ChannelChannelIdRoute: typeof ChannelChannelIdRoute
  WatchVideoIdRoute: typeof WatchVideoIdRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/channels': {
      id: '/channels'
      path: '/channels'
      fullPath: '/channels'
      preLoaderRoute: typeof ChannelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inbox': {
      id: '/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof InboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/later': {
      id: '/later'
      path: '/later'
      fullPath: '/later'
      preLoaderRoute: typeof LaterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library': {
      id: '/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/live': {
      id: '/live'
      path: '/live'
      fullPath: '/live'
      preLoaderRoute: typeof LiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pulse': {
      id: '/pulse'
      path: '/pulse'
      fullPath: '/pulse'
      preLoaderRoute: typeof PulseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shorts': {
      id: '/shorts'
      path: '/shorts'
      fullPath: '/shorts'
      preLoaderRoute: typeof ShortsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/you': {
      id: '/you'
      path: '/you'
      fullPath: '/you'
      preLoaderRoute: typeof YouRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/channel/$channelId': {
      id: '/channel/$channelId'
      path: '/channel/$channelId'
      fullPath: '/channel/$channelId'
      preLoaderRoute: typeof ChannelChannelIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/watch/$videoId': {
      id: '/watch/$videoId'
      path: '/watch/$videoId'
      fullPath: '/watch/$videoId'
      preLoaderRoute: typeof WatchVideoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChannelsRoute: ChannelsRoute,
  InboxRoute: InboxRoute,
  LaterRoute: LaterRoute,
  LibraryRoute: LibraryRoute,
  LiveRoute: LiveRoute,
  LoginRoute: LoginRoute,
  PulseRoute: PulseRoute,
  SettingsRoute: SettingsRoute,
  ShortsRoute: ShortsRoute,
  YouRoute: YouRoute,
  ChannelChannelIdRoute: ChannelChannelIdRoute,
  WatchVideoIdRoute: WatchVideoIdRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
